# Generated by Django 3.2.3 on 2022-03-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_student',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
