# Generated by Django 3.2.3 on 2022-03-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Student Name')),
                ('subject1', models.CharField(max_length=500)),
                ('subject2', models.CharField(max_length=500)),
                ('subject3', models.CharField(max_length=500)),
                ('cgpa', models.IntegerField(verbose_name='Percentage')),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
